sonar.projectKey=debate-ai
sonar.projectName=Debate AI Project
sonar.projectVersion=1.0

sonar.sources=backend,frontend

sonar.sourceEncoding=UTF-8

sonar.login=squ_0d6bcb6fa80a60ff8769fee3e2fc2e13795f466c